[project]
name = "2021-10-17_dev-python"
version = "0.1.0"
description = "Add a short description here"
authors = ["Junsok Huhh <anarinsk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
jupyter = ">=1.0.0,<1.1"
