[project]
name = "20240519_fastind-csv-loading"
version = "0.1.0"
description = "Add a short description here"
authors = ["Junsok Huhh <anarinsk@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]

[dependencies]
python = "3.11.*"
pandas = ">=2.2.2,<2.3"
jupyter = ">=1.0.0,<1.1"
joblib = ">=1.4.2,<1.5"
openpyxl = ">=3.1.2,<3.2"
